### ISSUE TITLE
Issue: t is not Object. Evaluating 'n in t'

### ISSUE THREAD

**Issue by jawwad22** [73R3WY/react-native-svg-animations#28] opened 2020-05-18 08:37 UTC
Getting this error when implementing any example 
![98349717_254967808891563_8178140218650525696_n](https://user-images.githubusercontent.com/21967262/82191859-9794f380-990c-11ea-80be-477b239c32f1.png)

Any Solutio

**Comment by 73R3WY** [comment] 2020-05-18 10:04
@jawwad22 , how did you define the `AnimatedSVGPath` in your view?

**Comment by jawwad22** [comment] 2020-05-18 10:13
import { AnimatedSVGPath } from 'react-native-svg-animations';

<AnimatedSVGPath
						strokeColor={"green"}
						duration={500}
						strokeWidth={10}
						strokeDashArray={[42.76482137044271, 42.76482137044271]}
						height={400}
						width={400}
						scale={0.75}
						delay={100}
						d={d}
						loop={false}
					/>

**Comment by jawwad22** [comment] 2020-05-19 09:16
i dont know whats the bug, but if i install the second last commit version package, its working fine

**Comment by 73R3WY** [comment] 2020-05-19 10:38
Thank you for the feedback @jawwad22 , I think I broke something with the latest update with the dependencies. Can you check using the latest version and modifying the files according to this pull request #26 . Sorry for the trouble caused by the latest version.

**Comment by 73R3WY** [comment] 2020-05-19 10:39
If #27 is the fix for this, I will immediately publish a new version. Thank you and good luck.

**Comment by jawwad22** [comment] 2020-05-20 10:23
ok, i will check and let you know

**Comment by 73R3WY** [comment] 2020-05-24 01:50
Closing this, merged #27 and updated npm package to `0.2.1`.

**Closed by 73R3WY** 2020-05-24 01:50 UTC
